import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden`}
      >
        <div className="w-screen h-screen flex flex-col bg-gradient-to-br from-blue-400 to-red-400">
          {/* Header with fixed height */}
          <div className="h-20 shrink-0">
            <Header />
          </div>

          {/* Content with sidebar and scrollable main */}
          <div className="flex flex-1 gap-4 p-4 overflow-hidden">
            <Sidebar />
            <main className="bg-white shadow-lg rounded-lg flex-1 flex flex-col overflow-y-auto p-4">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
