import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-screen h-screen bg-linear-to-br from-blue-400 to-red-400 flex flex-col gap-4 p-4">
          <Header />

          <div className="flex gap-4 w-full h-full">
            <Sidebar />
            <main className="bg-white shadow-lg rounded-lg flex-1 flex flex-col justify-center items-center">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
